version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: gr8pay-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123 
      MYSQL_DATABASE: gr8pay_db
      MYSQL_USER: gr8pay_user
      MYSQL_PASSWORD: admin123 
    ports:
      - "3307:3306"
    volumes:
      - gr8pay-mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: gr8pay-app
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: gr8pay_user
      DB_PASSWORD: admin123 
      DB_NAME: gr8pay_db
      NODE_ENV: production
    ports:
      - "8080:8080"
    command: >
      sh -c "node src/config/db.js --init && npm start"

volumes:
  gr8pay-mysql-data:
